(function(){var h={},mt={},c={id:"7f1c38424a58e6ebb23eeee705ad45af",dm:["edianzu.cn"],js:"tongji.baidu.com/hm-web/js/",etrk:[],icon:'/hmt/icon/21|gif|20|20',ctrk:true,align:1,nv:-1,vdur:1800000,age:31536000000,rec:0,rp:[],trust:1,vcard:7022289,qiao:7022289,lxb:0,conv:0,med:0,cvcc:{q:/tencent:\/\/|qq\.(com|htm)|kefu|openkf|swt|zoos|53kf|doyoo|looyu|leyu|zixun|chat|talk|openQQ|open_ask|online/i},cvcf:['checkvalidatecode','getvalidatecode'],apps:''};var p=void 0,r=!0,s=null,w=!1;mt.k={};mt.k.N=/msie (\d+\.\d+)/i.test(navigator.userAgent);mt.k.La=/msie (\d+\.\d+)/i.test(navigator.userAgent)?document.documentMode||+RegExp.$1:p;mt.k.cookieEnabled=navigator.cookieEnabled;mt.k.javaEnabled=navigator.javaEnabled();mt.k.language=navigator.language||navigator.browserLanguage||navigator.systemLanguage||navigator.userLanguage||"";mt.k.Qa=(window.screen.width||0)+"x"+(window.screen.height||0);mt.k.colorDepth=window.screen.colorDepth||0;mt.cookie={};
mt.cookie.set=function(a,d,f){var b;f.K&&(b=new Date,b.setTime(b.getTime()+f.K));document.cookie=a+"="+d+(f.domain?"; domain="+f.domain:"")+(f.path?"; path="+f.path:"")+(b?"; expires="+b.toGMTString():"")+(f.eb?"; secure":"")};mt.cookie.get=function(a){return(a=RegExp("(^| )"+a+"=([^;]*)(;|$)").exec(document.cookie))?a[2]:s};mt.p={};mt.p.W=function(a){return document.getElementById(a)};mt.p.va=function(a){var d;for(d="A";(a=a.parentNode)&&1==a.nodeType;)if(a.tagName==d)return a;return s};
(mt.p.R=function(){function a(){if(!a.D){a.D=r;for(var d=0,e=b.length;d<e;d++)b[d]()}}function d(){try{document.documentElement.doScroll("left")}catch(b){setTimeout(d,1);return}a()}var f=w,b=[],e;document.addEventListener?e=function(){document.removeEventListener("DOMContentLoaded",e,w);a()}:document.attachEvent&&(e=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",e),a())});(function(){if(!f)if(f=r,"complete"===document.readyState)a.D=r;else if(document.addEventListener)document.addEventListener("DOMContentLoaded",
e,w),window.addEventListener("load",a,w);else if(document.attachEvent){document.attachEvent("onreadystatechange",e);window.attachEvent("onload",a);var b=w;try{b=window.frameElement==s}catch(m){}document.documentElement.doScroll&&b&&d()}})();return function(d){a.D?d():b.push(d)}}()).D=w;mt.event={};mt.event.c=function(a,d,f){a.attachEvent?a.attachEvent("on"+d,function(b){f.call(a,b)}):a.addEventListener&&a.addEventListener(d,f,w)};
mt.event.preventDefault=function(a){a.preventDefault?a.preventDefault():a.returnValue=w};mt.m={};mt.m.parse=function(){return(new Function('return (" + source + ")'))()};
mt.m.stringify=function(){function a(a){/["\\\x00-\x1f]/.test(a)&&(a=a.replace(/["\\\x00-\x1f]/g,function(a){var b=f[a];if(b)return b;b=a.charCodeAt();return"\\u00"+Math.floor(b/16).toString(16)+(b%16).toString(16)}));return'"'+a+'"'}function d(a){return 10>a?"0"+a:a}var f={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return function(b){switch(typeof b){case "undefined":return"undefined";case "number":return isFinite(b)?String(b):"null";case "string":return a(b);case "boolean":return String(b);
default:if(b===s)return"null";if(b instanceof Array){var e=["["],f=b.length,m,g,k;for(g=0;g<f;g++)switch(k=b[g],typeof k){case "undefined":case "function":case "unknown":break;default:m&&e.push(","),e.push(mt.m.stringify(k)),m=1}e.push("]");return e.join("")}if(b instanceof Date)return'"'+b.getFullYear()+"-"+d(b.getMonth()+1)+"-"+d(b.getDate())+"T"+d(b.getHours())+":"+d(b.getMinutes())+":"+d(b.getSeconds())+'"';m=["{"];g=mt.m.stringify;for(f in b)if(Object.prototype.hasOwnProperty.call(b,f))switch(k=
b[f],typeof k){case "undefined":case "unknown":case "function":break;default:e&&m.push(","),e=1,m.push(g(f)+":"+g(k))}m.push("}");return m.join("")}}}();mt.lang={};mt.lang.d=function(a,d){return"[object "+d+"]"==={}.toString.call(a)};mt.lang.ab=function(a){return mt.lang.d(a,"Number")&&isFinite(a)};mt.lang.cb=function(a){return mt.lang.d(a,"String")};mt.localStorage={};
mt.localStorage.I=function(){if(!mt.localStorage.g)try{mt.localStorage.g=document.createElement("input"),mt.localStorage.g.type="hidden",mt.localStorage.g.style.display="none",mt.localStorage.g.addBehavior("#default#userData"),document.getElementsByTagName("head")[0].appendChild(mt.localStorage.g)}catch(a){return w}return r};
mt.localStorage.set=function(a,d,f){var b=new Date;b.setTime(b.getTime()+f||31536E6);try{window.localStorage?(d=b.getTime()+"|"+d,window.localStorage.setItem(a,d)):mt.localStorage.I()&&(mt.localStorage.g.expires=b.toUTCString(),mt.localStorage.g.load(document.location.hostname),mt.localStorage.g.setAttribute(a,d),mt.localStorage.g.save(document.location.hostname))}catch(e){}};
mt.localStorage.get=function(a){if(window.localStorage){if(a=window.localStorage.getItem(a)){var d=a.indexOf("|"),f=a.substring(0,d)-0;if(f&&f>(new Date).getTime())return a.substring(d+1)}}else if(mt.localStorage.I())try{return mt.localStorage.g.load(document.location.hostname),mt.localStorage.g.getAttribute(a)}catch(b){}return s};
mt.localStorage.remove=function(a){if(window.localStorage)window.localStorage.removeItem(a);else if(mt.localStorage.I())try{mt.localStorage.g.load(document.location.hostname),mt.localStorage.g.removeAttribute(a),mt.localStorage.g.save(document.location.hostname)}catch(d){}};mt.sessionStorage={};mt.sessionStorage.set=function(a,d){if(window.sessionStorage)try{window.sessionStorage.setItem(a,d)}catch(f){}};
mt.sessionStorage.get=function(a){return window.sessionStorage?window.sessionStorage.getItem(a):s};mt.sessionStorage.remove=function(a){window.sessionStorage&&window.sessionStorage.removeItem(a)};mt.T={};mt.T.log=function(a,d){var f=new Image,b="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[b]=f;f.onload=f.onerror=f.onabort=function(){f.onload=f.onerror=f.onabort=s;f=window[b]=s;d&&d(a)};f.src=a};mt.H={};
mt.H.Da=function(){var a="";if(navigator.plugins&&navigator.mimeTypes.length){var d=navigator.plugins["Shockwave Flash"];d&&d.description&&(a=d.description.replace(/^.*\s+(\S+)\s+\S+$/,"$1"))}else if(window.ActiveXObject)try{if(d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))(a=d.GetVariable("$version"))&&(a=a.replace(/^.*\s+(\d+),(\d+).*$/,"$1.$2"))}catch(f){}return a};
mt.H.pa=function(a,d,f,b,e){return'<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="'+a+'" width="'+f+'" height="'+b+'"><param name="movie" value="'+d+'" /><param name="flashvars" value="'+(e||"")+'" /><param name="allowscriptaccess" value="always" /><embed type="application/x-shockwave-flash" name="'+a+'" width="'+f+'" height="'+b+'" src="'+d+'" flashvars="'+(e||"")+'" allowscriptaccess="always" /></object>'};mt.url={};
mt.url.l=function(a,d){var f=a.match(RegExp("(^|&|\\?|#)("+d+")=([^&#]*)(&|$|#)",""));return f?f[3]:s};mt.url.$a=function(a){return(a=a.match(/^(https?:)\/\//))?a[1]:s};mt.url.za=function(a){return(a=a.match(/^(https?:\/\/)?([^\/\?#]*)/))?a[2].replace(/.*@/,""):s};mt.url.Y=function(a){return(a=mt.url.za(a))?a.replace(/:\d+$/,""):a};mt.url.Za=function(a){return(a=a.match(/^(https?:\/\/)?[^\/]*(.*)/))?a[2].replace(/[\?#].*/,"").replace(/^$/,"/"):s};
h.i={Ka:"http://tongji.baidu.com/hm-web/welcome/ico",Q:"hm.baidu.com/hm.gif",ha:"baidu.com",Ha:"hmmd",Ia:"hmpl",Ga:"hmkw",Ea:"hmci",Ja:"hmsr",Fa:"hmcu",z:0,o:Math.round(+new Date/1E3),protocol:"https:"===document.location.protocol?"https:":"http:",bb:0,na:6E5,oa:10,U:1024,ma:1,w:2147483647,da:"cc cf ci ck cl cm cp cu cw ds ep et fl ja ln lo lt nv rnd si st su v cv lv api u tt".split(" ")};
(function(){var a={s:{},c:function(a,f){this.s[a]=this.s[a]||[];this.s[a].push(f)},B:function(a,f){this.s[a]=this.s[a]||[];for(var b=this.s[a].length,e=0;e<b;e++)this.s[a][e](f)}};return h.r=a})();
(function(){function a(a,b){var e=document.createElement("script");e.charset="utf-8";d.d(b,"Function")&&(e.readyState?e.onreadystatechange=function(){if("loaded"===e.readyState||"complete"===e.readyState)e.onreadystatechange=s,b()}:e.onload=function(){b()});e.src=a;var l=document.getElementsByTagName("script")[0];l.parentNode.insertBefore(e,l)}var d=mt.lang;return h.load=a})();
(function(){function a(){var a="";h.b.a.nv?(a=encodeURIComponent(document.referrer),window.sessionStorage?f.set("Hm_from_"+c.id,a):d.set("Hm_from_"+c.id,a,864E5)):a=(window.sessionStorage?f.get("Hm_from_"+c.id):d.get("Hm_from_"+c.id))||"";return a}var d=mt.localStorage,f=mt.sessionStorage;return h.V=a})();
(function(){var a=h.i,d=mt.H,f={init:function(){if(""!==c.icon){var b;b=c.icon.split("|");var e=a.Ka+"?s="+c.id,f=("http:"==a.protocol?"http://eiv":"https://bs")+".baidu.com"+b[0]+"."+b[1];switch(b[1]){case "swf":b=d.pa("HolmesIcon"+a.o,f,b[2],b[3],"s="+e);break;case "gif":b='<a href="'+e+'" target="_blank"><img border="0" src="'+f+'" width="'+b[2]+'" height="'+b[3]+'"></a>';break;default:b='<a href="'+e+'" target="_blank">'+b[0]+"</a>"}document.write(b)}}};h.r.c("pv-b",f.init);return f})();
(function(){var a=mt.p,d=mt.event,f=mt.k,b=h.i,e=[],l={ea:function(){c.ctrk&&(d.c(document,"mouseup",l.la()),d.c(window,"unload",function(){l.F()}),setInterval(function(){l.F()},b.na))},la:function(){return function(a){a=l.wa(a);if(""!==a){var d=(b.protocol+"//"+b.Q+"?"+h.b.ca().replace(/ep=[^&]*/,"ep="+encodeURIComponent("["+a+"]"))).length;d+(b.w+"").length>b.U||(d+encodeURIComponent(e.join(",")+(e.length?",":"")).length+(b.w+"").length>b.U&&l.F(),e.push(a),(e.length>=b.oa||/t:a/.test(a))&&l.F())}}},
wa:function(d){if(0===b.ma){var e=d.target||d.srcElement,k=e.tagName.toLowerCase();if("embed"==k||"object"==k)return""}f.N?(e=Math.max(document.documentElement.scrollTop,document.body.scrollTop),k=Math.max(document.documentElement.scrollLeft,document.body.scrollLeft),k=d.clientX+k,e=d.clientY+e):(k=d.pageX,e=d.pageY);var n=window.innerWidth||document.documentElement.clientWidth||document.body.offsetWidth;switch(c.align){case 1:k-=n/2;break;case 2:k-=n}k="{x:"+k+",y:"+e+",";e=d.target||d.srcElement;
return k=(d="a"==e.tagName.toLowerCase()?e:a.va(e))?k+("t:a,u:"+encodeURIComponent(d.href)+"}"):k+"t:b}"},F:function(){0!==e.length&&(h.b.a.et=2,h.b.a.ep="["+e.join(",")+"]",h.b.j(),e=[])}};h.r.c("pv-b",l.ea);return l})();
(function(){var a=mt.p,d=h.i,f=h.load,b=h.V;h.r.c("pv-b",function(){c.rec&&a.R(function(){for(var e=0,l=c.rp.length;e<l;e++){var m=c.rp[e][0],g=c.rp[e][1],k=a.W("hm_t_"+m);if(g&&!(2==g&&!k||k&&""!==k.innerHTML))k="",k=Math.round(Math.random()*d.w),k=4==g?"http://crs.baidu.com/hl.js?"+["siteId="+c.id,"planId="+m,"rnd="+k].join("&"):"http://crs.baidu.com/t.js?"+["siteId="+c.id,"planId="+m,"from="+b(),"referer="+encodeURIComponent(document.referrer),"title="+encodeURIComponent(document.title),"rnd="+
k].join("&"),f(k)}})})})();(function(){var a=h.i,d=h.load,f=h.V;h.r.c("pv-b",function(){if(c.trust&&c.vcard){var b=a.protocol+"//trust.baidu.com/vcard/v.js?"+["siteid="+c.vcard,"url="+encodeURIComponent(document.location.href),"source="+f(),"rnd="+Math.round(Math.random()*a.w),"hm=1"].join("&");d(b)}})})();
(function(){function a(){return function(){h.b.a.nv=0;h.b.a.st=4;h.b.a.et=3;h.b.a.ep=h.J.Ba()+","+h.J.ya();h.b.j()}}function d(){clearTimeout(B);var a;z&&(a="visible"==document[z]);C&&(a=!document[C]);g="undefined"==typeof a?r:a;if((!m||!k)&&g&&n)u=r,q=+new Date;else if(m&&k&&(!g||!n))u=w,t+=+new Date-q;m=g;k=n;B=setTimeout(d,100)}function f(a){var k=document,q="";if(a in k)q=a;else for(var b=["webkit","ms","moz","o"],d=0;d<b.length;d++){var e=b[d]+a.charAt(0).toUpperCase()+a.slice(1);if(e in k){q=
e;break}}return q}function b(a){if(!("focus"==a.type||"blur"==a.type)||!(a.target&&a.target!=window))n="focus"==a.type||"focusin"==a.type?r:w,d()}var e=mt.event,l=h.r,m=r,g=r,k=r,n=r,v=+new Date,q=v,t=0,u=r,z=f("visibilityState"),C=f("hidden"),B;d();(function(){var a=z.replace(/[vV]isibilityState/,"visibilitychange");e.c(document,a,d);e.c(window,"pageshow",d);e.c(window,"pagehide",d);"object"==typeof document.onfocusin?(e.c(document,"focusin",b),e.c(document,"focusout",b)):(e.c(window,"focus",b),
e.c(window,"blur",b))})();h.J={Ba:function(){return+new Date-v},ya:function(){return u?+new Date-q+t:t}};l.c("pv-b",function(){e.c(window,"unload",a())});return h.J})();
(function(){var a=mt.lang,d=h.i,f=h.load,b={Ma:function(b){if((window._dxt===p||a.d(window._dxt,"Array"))&&"undefined"!==typeof h.b){var l=h.b.L();f([d.protocol,"//datax.baidu.com/x.js?si=",c.id,"&dm=",encodeURIComponent(l)].join(""),b)}},Wa:function(b){if(a.d(b,"String")||a.d(b,"Number"))window._dxt=window._dxt||[],window._dxt.push(["_setUserId",b])}};return h.qa=b})();
(function(){function a(k){for(var b in k)if({}.hasOwnProperty.call(k,b)){var d=k[b];f.d(d,"Object")||f.d(d,"Array")?a(d):k[b]=String(d)}}function d(a){return a.replace?a.replace(/'/g,"'0").replace(/\*/g,"'1").replace(/!/g,"'2"):a}var f=mt.lang,b=mt.m,e=h.i,l=h.r,m=h.qa,g={A:[],G:0,aa:w,init:function(){g.e=0;l.c("pv-b",function(){g.ra();g.ta()});l.c("pv-d",g.ua);l.c("stag-b",function(){h.b.a.api=g.e||g.G?g.e+"_"+g.G:""});l.c("stag-d",function(){h.b.a.api=0;g.e=0;g.G=0})},ra:function(){var a=window._hmt||
[];if(!a||f.d(a,"Array"))window._hmt={id:c.id,cmd:{},push:function(){for(var a=window._hmt,k=0;k<arguments.length;k++){var b=arguments[k];f.d(b,"Array")&&(a.cmd[a.id].push(b),"_setAccount"===b[0]&&(1<b.length&&/^[0-9a-f]{32}$/.test(b[1]))&&(b=b[1],a.id=b,a.cmd[b]=a.cmd[b]||[]))}}},window._hmt.cmd[c.id]=[],window._hmt.push.apply(window._hmt,a)},ta:function(){var a=window._hmt;if(a&&a.cmd&&a.cmd[c.id])for(var b=a.cmd[c.id],d=/^_track(Event|MobConv|Order|RTEvent)$/,q=0,e=b.length;q<e;q++){var f=b[q];
d.test(f[0])?g.A.push(f):g.P(f)}a.cmd[c.id]={push:g.P}},ua:function(){if(0<g.A.length)for(var a=0,b=g.A.length;a<b;a++)g.P(g.A[a]);g.A=s},P:function(a){var b=a[0];if(g.hasOwnProperty(b)&&f.d(g[b],"Function"))g[b](a)},_setAccount:function(a){1<a.length&&/^[0-9a-f]{32}$/.test(a[1])&&(g.e|=1)},_setAutoPageview:function(a){if(1<a.length&&(a=a[1],w===a||r===a))g.e|=2,h.b.Z=a},_trackPageview:function(a){if(1<a.length&&a[1].charAt&&"/"===a[1].charAt(0)){g.e|=4;h.b.a.et=0;h.b.a.ep="";h.b.M?(h.b.a.nv=0,h.b.a.st=
4):h.b.M=r;var b=h.b.a.u,d=h.b.a.su;h.b.a.u=e.protocol+"//"+document.location.host+a[1];g.aa||(h.b.a.su=document.location.href);h.b.j();h.b.a.u=b;h.b.a.su=d}},_trackEvent:function(a){2<a.length&&(g.e|=8,h.b.a.nv=0,h.b.a.st=4,h.b.a.et=4,h.b.a.ep=d(a[1])+"*"+d(a[2])+(a[3]?"*"+d(a[3]):"")+(a[4]?"*"+d(a[4]):""),h.b.j())},_setCustomVar:function(a){if(!(4>a.length)){var b=a[1],e=a[4]||3;if(0<b&&6>b&&0<e&&4>e){g.G++;for(var q=(h.b.a.cv||"*").split("!"),f=q.length;f<b-1;f++)q.push("*");q[b-1]=e+"*"+d(a[2])+
"*"+d(a[3]);h.b.a.cv=q.join("!");a=h.b.a.cv.replace(/[^1](\*[^!]*){2}/g,"*").replace(/((^|!)\*)+$/g,"");""!==a?h.b.setData("Hm_cv_"+c.id,encodeURIComponent(a),c.age):h.b.Pa("Hm_cv_"+c.id)}}},_setReferrerOverride:function(a){1<a.length&&(h.b.a.su=a[1].charAt&&"/"===a[1].charAt(0)?e.protocol+"//"+window.location.host+a[1]:a[1],g.aa=r)},_trackOrder:function(d){d=d[1];f.d(d,"Object")&&(a(d),g.e|=16,h.b.a.nv=0,h.b.a.st=4,h.b.a.et=94,h.b.a.ep=b.stringify(d),h.b.j())},_trackMobConv:function(a){if(a={webim:1,
tel:2,map:3,sms:4,callback:5,share:6}[a[1]])g.e|=32,h.b.a.et=93,h.b.a.ep=a,h.b.j()},_trackRTPageview:function(d){d=d[1];f.d(d,"Object")&&(a(d),d=b.stringify(d),512>=encodeURIComponent(d).length&&(g.e|=64,h.b.a.rt=d))},_trackRTEvent:function(d){d=d[1];if(f.d(d,"Object")){a(d);d=encodeURIComponent(b.stringify(d));var l=function(a){var b=h.b.a.rt;g.e|=128;h.b.a.et=90;h.b.a.rt=a;h.b.j();h.b.a.rt=b},m=d.length;if(900>=m)l.call(this,d);else for(var m=Math.ceil(m/900),q="block|"+Math.round(Math.random()*
e.w).toString(16)+"|"+m+"|",t=[],u=0;u<m;u++)t.push(u),t.push(d.substring(900*u,900*u+900)),l.call(this,q+t.join("|")),t=[]}},_setUserId:function(a){a=a[1];m.Ma();m.Wa(a)}};g.init();h.ia=g;return h.ia})();
(function(){function a(){"undefined"===typeof window["_bdhm_loaded_"+c.id]&&(window["_bdhm_loaded_"+c.id]=r,this.a={},this.Z=r,this.M=w,this.init())}var d=mt.url,f=mt.T,b=mt.H,e=mt.lang,l=mt.cookie,m=mt.k,g=mt.localStorage,k=mt.sessionStorage,n=h.i,v=h.r;a.prototype={O:function(a,b){a="."+a.replace(/:\d+/,"");b="."+b.replace(/:\d+/,"");var d=a.indexOf(b);return-1<d&&d+b.length===a.length},ba:function(a,b){a=a.replace(/^https?:\/\//,"");return 0===a.indexOf(b)},C:function(a){for(var b=0;b<c.dm.length;b++)if(-1<
c.dm[b].indexOf("/")){if(this.ba(a,c.dm[b]))return r}else{var e=d.Y(a);if(e&&this.O(e,c.dm[b]))return r}return w},L:function(){for(var a=document.location.hostname,b=0,d=c.dm.length;b<d;b++)if(this.O(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[\/\?#].*/,"");return a},X:function(){for(var a=0,b=c.dm.length;a<b;a++){var d=c.dm[a];if(-1<d.indexOf("/")&&this.ba(document.location.href,d))return d.replace(/^[^\/]+(\/.*)/,"$1")+"/"}return"/"},Ca:function(){if(!document.referrer)return n.o-n.z>c.vdur?1:4;
var a=w;this.C(document.referrer)&&this.C(document.location.href)?a=r:(a=d.Y(document.referrer),a=this.O(a||"",document.location.hostname));return a?n.o-n.z>c.vdur?1:4:3},getData:function(a){try{return l.get(a)||k.get(a)||g.get(a)}catch(b){}},setData:function(a,b,d){try{l.set(a,b,{domain:this.L(),path:this.X(),K:d}),d?g.set(a,b,d):k.set(a,b)}catch(e){}},Pa:function(a){try{l.set(a,"",{domain:this.L(),path:this.X(),K:-1}),k.remove(a),g.remove(a)}catch(b){}},Ua:function(){var a,b,d,e,f;n.z=this.getData("Hm_lpvt_"+
c.id)||0;13===n.z.length&&(n.z=Math.round(n.z/1E3));b=this.Ca();a=4!==b?1:0;if(d=this.getData("Hm_lvt_"+c.id)){e=d.split(",");for(f=e.length-1;0<=f;f--)13===e[f].length&&(e[f]=""+Math.round(e[f]/1E3));for(;2592E3<n.o-e[0];)e.shift();f=4>e.length?2:3;for(1===a&&e.push(n.o);4<e.length;)e.shift();d=e.join(",");e=e[e.length-1]}else d=n.o,e="",f=1;this.setData("Hm_lvt_"+c.id,d,c.age);this.setData("Hm_lpvt_"+c.id,n.o);d=n.o===this.getData("Hm_lpvt_"+c.id)?"1":"0";if(0===c.nv&&this.C(document.location.href)&&
(""===document.referrer||this.C(document.referrer)))a=0,b=4;this.a.nv=a;this.a.st=b;this.a.cc=d;this.a.lt=e;this.a.lv=f},ca:function(){for(var a=[],b=this.a.et,d=0,e=n.da.length;d<e;d++){var f=n.da[d],g=this.a[f];"undefined"!==typeof g&&""!==g&&("tt"!==f||"tt"===f&&0===b)&&a.push(f+"="+encodeURIComponent(g))}this.a.rt&&(0===b?a.push("rt="+encodeURIComponent(this.a.rt)):90===b&&a.push("rt="+this.a.rt));return a.join("&")},Va:function(){this.Ua();this.a.si=c.id;this.a.su=document.referrer;this.a.ds=
m.Qa;this.a.cl=m.colorDepth+"-bit";this.a.ln=m.language;this.a.ja=m.javaEnabled?1:0;this.a.ck=m.cookieEnabled?1:0;this.a.lo="number"===typeof _bdhm_top?1:0;this.a.fl=b.Da();this.a.v="1.1.26";this.a.cv=decodeURIComponent(this.getData("Hm_cv_"+c.id)||"");this.a.tt=document.title||"";var a=document.location.href;this.a.cm=d.l(a,n.Ha)||"";this.a.cp=d.l(a,n.Ia)||"";this.a.cw=d.l(a,n.Ga)||"";this.a.ci=d.l(a,n.Ea)||"";this.a.cf=d.l(a,n.Ja)||"";this.a.cu=d.l(a,n.Fa)||""},init:function(){try{this.Va(),0===
this.a.nv?this.Sa():this.S(".*"),h.b=this,this.ka(),v.B("pv-b"),this.Ra()}catch(a){var b=[];b.push("si="+c.id);b.push("n="+encodeURIComponent(a.name));b.push("m="+encodeURIComponent(a.message));b.push("r="+encodeURIComponent(document.referrer));f.log(n.protocol+"//"+n.Q+"?"+b.join("&"))}},Ra:function(){function a(){v.B("pv-d")}this.Z?(this.M=r,this.a.et=0,this.a.ep="",this.j(a)):a()},j:function(a){var b=this;b.a.rnd=Math.round(Math.random()*n.w);v.B("stag-b");var d=n.protocol+"//"+n.Q+"?"+b.ca();
v.B("stag-d");b.ga(d);f.log(d,function(d){b.S(d);e.d(a,"Function")&&a.call(b)})},ka:function(){var a=document.location.hash.substring(1),b=RegExp(c.id),e=-1<document.referrer.indexOf(n.ha),f=d.l(a,"jn"),g=/^heatlink$|^select$/.test(f);a&&(b.test(a)&&e&&g)&&(this.a.rnd=Math.round(Math.random()*n.w),a=document.createElement("script"),a.setAttribute("type","text/javascript"),a.setAttribute("charset","utf-8"),a.setAttribute("src",n.protocol+"//"+c.js+f+".js?"+this.a.rnd),f=document.getElementsByTagName("script")[0],
f.parentNode.insertBefore(a,f))},ga:function(a){var b=k.get("Hm_unsent_"+c.id)||"",d=this.a.u?"":"&u="+encodeURIComponent(document.location.href),b=encodeURIComponent(a.replace(/^https?:\/\//,"")+d)+(b?","+b:"");k.set("Hm_unsent_"+c.id,b)},S:function(a){var b=k.get("Hm_unsent_"+c.id)||"";b&&(a=encodeURIComponent(a.replace(/^https?:\/\//,"")),a=RegExp(a.replace(/([\*\(\)])/g,"\\$1")+"(%26u%3D[^,]*)?,?","g"),(b=b.replace(a,"").replace(/,$/,""))?k.set("Hm_unsent_"+c.id,b):k.remove("Hm_unsent_"+c.id))},
Sa:function(){var a=this,b=k.get("Hm_unsent_"+c.id);if(b)for(var b=b.split(","),d=function(b){f.log(n.protocol+"//"+decodeURIComponent(b),function(b){a.S(b)})},e=0,g=b.length;e<g;e++)d(b[e])}};return new a})();var x=h.i,y=h.load;if(c.apps){var A=[x.protocol,"//ers.baidu.com/app/s.js?"];A.push(c.apps);y(A.join(""))}var D=h.i,E=h.load;if(c.conv&&"http:"===D.protocol){var F=["http://page.baidu.com/conversion_js.php?sid="];F.push(c.conv);E(F.join(""))}var G=h.i,H=h.load;
c.lxb&&H([G.protocol,"//lxbjs.baidu.com/lxb.js?sid=",c.lxb].join(""));var I=h.load,J=h.i.protocol;if(c.qiao){for(var K=[J+"//goutong.baidu.com/site/"],L=c.id,M=5381,N=L.length,O=0;O<N;O++)M=(33*M+Number(L.charCodeAt(O)))%4294967296;2147483648<M&&(M-=2147483648);K.push(M%1E3+"/");K.push(c.id+"/b.js");K.push("?siteId="+c.qiao);I(K.join(""))}
(function(){var a=mt.p,d=mt.event,f=mt.url,b=mt.m;try{if(window.performance&&performance.timing&&"undefined"!==typeof h.b){var e=+new Date,l=function(a){var b=performance.timing,d=b[a+"Start"]?b[a+"Start"]:0;a=b[a+"End"]?b[a+"End"]:0;return{start:d,end:a,value:0<a-d?a-d:0}},m=s;a.R(function(){m=+new Date});var g=function(){var a,d,g;g=l("navigation");d=l("request");g={netAll:d.start-g.start,netDns:l("domainLookup").value,netTcp:l("connect").value,srv:l("response").start-d.start,dom:performance.timing.domInteractive-
performance.timing.fetchStart,loadEvent:l("loadEvent").end-g.start};a=document.referrer;var k=a.match(/^(http[s]?:\/\/)?([^\/]+)(.*)/)||[],u=s;d=s;if("www.baidu.com"===k[2]||"m.baidu.com"===k[2])u=f.l(a,"qid"),d=f.l(a,"click_t");a=u;g.qid=a!=s?a:"";d!=s?(g.bdDom=m?m-d:0,g.bdRun=e-d,g.bdDef=l("navigation").start-d):(g.bdDom=0,g.bdRun=0,g.bdDef=0);h.b.a.et=87;h.b.a.ep=b.stringify(g);h.b.j()};d.c(window,"load",function(){setTimeout(g,500)})}}catch(k){}})();
(function(){var a=h.i,d={init:function(){try{if("http:"===a.protocol){var b=document.createElement("IFRAME");b.setAttribute("src","http://boscdn.bpc.baidu.com/v1/holmes-moplus/mp-cdn.html");b.style.display="none";b.style.width="1";b.style.height="1";b.Ya="0";document.body.appendChild(b)}}catch(d){}}},f=navigator.userAgent.toLowerCase();-1<f.indexOf("android")&&-1===f.indexOf("micromessenger")&&d.init()})();
(function(){var a=mt.k,d=mt.lang,f=mt.event,b=mt.m;if("undefined"!==typeof h.b&&(c.med||(!a.N||7<a.La)&&c.cvcc)){var e,l,m,g,k=function(a){if(a.item){for(var b=a.length,d=Array(b);b--;)d[b]=a[b];return d}return[].slice.call(a)},n=function(a,b){for(var d in a)if(a.hasOwnProperty(d)&&b.call(a,d,a[d])===w)return w},v=function(a,f){var g={};g.n=e;g.t="clk";g.v=a;if(f){var l=f.getAttribute("href"),k=f.getAttribute("onclick")?""+f.getAttribute("onclick"):s,n=f.getAttribute("id")||"";m.test(l)?(g.sn="mediate",
g.snv=l):d.d(k,"String")&&m.test(k)&&(g.sn="wrap",g.snv=k);g.id=n}h.b.a.et=86;h.b.a.ep=b.stringify(g);h.b.j();for(g=+new Date;400>=+new Date-g;);};if(c.med)l="/zoosnet",e="swt",m=/swt|zixun|call|chat|zoos|business|talk|kefu|openkf|online|\/LR\/Chatpre\.aspx/i,g={click:function(){for(var a=[],b=k(document.getElementsByTagName("a")),b=[].concat.apply(b,k(document.getElementsByTagName("area"))),b=[].concat.apply(b,k(document.getElementsByTagName("img"))),d,e,f=0,g=b.length;f<g;f++)d=b[f],e=d.getAttribute("onclick"),
d=d.getAttribute("href"),(m.test(e)||m.test(d))&&a.push(b[f]);return a}};else if(c.cvcc){l="/other-comm";e="other";m=c.cvcc.q||p;var q=c.cvcc.id||p;g={click:function(){for(var a=[],b=k(document.getElementsByTagName("a")),b=[].concat.apply(b,k(document.getElementsByTagName("area"))),b=[].concat.apply(b,k(document.getElementsByTagName("img"))),d,e,f,g=0,l=b.length;g<l;g++)d=b[g],m!==p?(e=d.getAttribute("onclick"),f=d.getAttribute("href"),q?(d=d.getAttribute("id"),(m.test(e)||m.test(f)||q.test(d))&&
a.push(b[g])):(m.test(e)||m.test(f))&&a.push(b[g])):q!==p&&(d=d.getAttribute("id"),q.test(d)&&a.push(b[g]));return a}}}if("undefined"!==typeof g&&"undefined"!==typeof m){var t;l+=/\/$/.test(l)?"":"/";var u=function(a,b){if(t===b)return v(l+a,b),w;if(d.d(b,"Array")||d.d(b,"NodeList"))for(var e=0,f=b.length;e<f;e++)if(t===b[e])return v(l+a+"/"+(e+1),b[e]),w};f.c(document,"mousedown",function(a){a=a||window.event;t=a.target||a.srcElement;var b={};for(n(g,function(a,e){b[a]=d.d(e,"Function")?e():document.getElementById(e)});t&&
t!==document&&n(b,u)!==w;)t=t.parentNode})}}})();(function(){var a=mt.p,d=mt.lang,f=mt.event,b=mt.m;if("undefined"!==typeof h.b&&d.d(c.cvcf,"Array")&&0<c.cvcf.length){var e={fa:function(){for(var b=c.cvcf.length,d,g=0;g<b;g++)(d=a.W(decodeURIComponent(c.cvcf[g])))&&f.c(d,"click",e.sa())},sa:function(){return function(){h.b.a.et=86;var a={n:"form",t:"clk"};a.id=this.id;h.b.a.ep=b.stringify(a);h.b.j()}}};a.R(function(){e.fa()})}})();
(function(){var a=mt.event,d=mt.m;if(c.med&&"undefined"!==typeof h.b){var f=+new Date,b={n:"anti",sb:0,kb:0,clk:0},e=function(){h.b.a.et=86;h.b.a.ep=d.stringify(b);h.b.j()};a.c(document,"click",function(){b.clk++});a.c(document,"keyup",function(){b.kb=1});a.c(window,"scroll",function(){b.sb++});a.c(window,"unload",function(){b.t=+new Date-f;e()});a.c(window,"load",function(){setTimeout(e,5E3)})}})();
(function(){function a(){this.f=s}var d=mt.T,f=mt.k;a.prototype={Na:function(a){if(this.f)this.h(a,0);else if(this.isSupported()){try{this.f=new ActiveXObject("BDEXIE.BDExExtension.1"),this.$=r}catch(b){this.$=w}this.$?this.h(a,0):this.h(a,-1)}else this.h(a,-1)},Xa:function(){this.f&&delete this.f;this.f=s},Ta:function(a,b,d){if(this.f&&"SetLocalCache"in this.f)try{this.f.SetLocalCache(a,b)===p&&this.h(d,0)}catch(f){this.h(d,-1)}else this.h(d,-1)},Aa:function(a,b){if(this.f&&"GetLocalCache"in this.f)try{this.h(b,
this.f.GetLocalCache(a))}catch(d){this.h(b,"")}else this.h(b,"")},xa:function(a){if(this.f&&"GetCryptStr"in this.f)try{this.h(a,this.f.GetCryptStr("strEncryptID1"))}catch(b){this.h(a,"")}else this.h(a,"")},h:function(a,b){"function"===typeof a&&a(b,this)},isSupported:function(){if(window.ActiveXObject||"ActiveXObject"in window)try{return!!new ActiveXObject("BDEXIE.BDExExtension.1")}catch(a){}return w},Oa:function(){var a=this;this.xa(function(b){b!==p&&""!==b&&(d.log("//datax.baidu.com/x.gif?dm="+
encodeURIComponent("datax.baidu.com/webadapter/guid")+"&ac="+encodeURIComponent(b)+"&v=hm-webadapter-0.0.1&rnd="+Math.round(2147483647*Math.random())),a.Ta("hmKey",+new Date,function(){a.Xa()}))})}};if(f.N&&/^http(s)?:$/.test(document.location.protocol)){var b=new a;b.Na(function(a){0===a&&b.Aa("hmKey",function(a){a=+a;(isNaN(a)||6048E5<+new Date-a)&&b.Oa()})})}})();})();
